// GENERATED by Scripts/gen-versions.sh from versions.env — DO NOT EDIT.
// The single source of truth for all version numbers is versions.env.

/// Version numbers surfaced to the app (UI, updater) — mirrored from versions.env.
public enum Versions {
    /// Silo release (marketing) version. Mirrors `Info.plist` `CFBundleShortVersionString`.
    public static let silo = "0.4.1"
    /// GitHub repo (owner/name) — app releases (updater) + wine-cx-* runtime builds.
    public static let githubRepo = "mikaelhug/Silo"
    /// CrossOver FOSS source version the Wine runtime is built from (CI/build input only — the app
    /// downloads the latest published wine-cx-* release at runtime).
    public static let crossoverVersion = "26.2.0"
}
