#!/usr/bin/env bash
# Generate Sources/SiloKit/Versions.swift from versions.env (the single source of truth).
# Run automatically by build-app.sh; the generated file is committed so a clean checkout compiles.
set -euo pipefail
cd "$(dirname "$0")/.."

set -a; . ./versions.env; set +a

OUT="Sources/SiloKit/Versions.swift"
cat > "$OUT" <<EOF
// GENERATED by Scripts/gen-versions.sh from versions.env — DO NOT EDIT.
// The single source of truth for all version numbers is versions.env.

/// Version numbers surfaced to the app (UI, updater) — mirrored from versions.env.
public enum Versions {
    /// Silo release (marketing) version. Mirrors \`Info.plist\` \`CFBundleShortVersionString\`.
    public static let silo = "${SILO_VERSION}"
    /// GitHub repo (owner/name) — app releases (updater) + wine-cx-* runtime builds.
    public static let githubRepo = "${SILO_GITHUB_REPO}"
    /// CrossOver FOSS source version the Wine runtime is built from (CI/build input only — the app
    /// downloads the latest published wine-cx-* release at runtime).
    public static let crossoverVersion = "${CROSSOVER_VERSION}"
}
EOF

echo "wrote $OUT (Silo ${SILO_VERSION})"
