import Foundation

/// Builds a standalone macOS `.app` that launches a Silo library game — double-clickable from the Desktop,
/// Spotlight, Dock, or Launchpad without first opening Silo's window. Unlike the old (removed) shortcut, this
/// does NOT snapshot a launch plan or exec wine itself: its launch script simply `open`s a `silo://play/…`
/// deep link, so the running (or freshly-launched) Silo resolves the game's backend, prefix, and — for a
/// Steam title — the co-resident Steam client fresh at click time. That keeps a shortcut correct forever
/// (Automatic backend, a later learned-DXMT reroute, a moved bottle) and works for Steam and manual games
/// alike, with no prefix pre-seeding.
///
/// The bundle is a background agent (`LSUIElement`) — the stub hands off to LaunchServices and exits, so it
/// never flashes a Dock tile; Silo coming to the front IS the feedback. Pure builders (`infoPlist`,
/// `launchScript`) are unit-tested; `write` performs the bundle I/O.
public struct GameShortcut: Sendable {
    /// The game's display name (shown on the bundle and its Finder label).
    public let name: String
    /// The deep link the bundle opens.
    public let link: SiloDeepLink

    public init(name: String, link: SiloDeepLink) {
        self.name = name
        self.link = link
    }

    /// The `CFBundleIdentifier` prefix every Silo shortcut carries — used to tell OUR shortcut `.app`s
    /// (safe to replace) apart from an unrelated item that happens to share the file name.
    static let bundleIDPrefix = "com.mikael.silo.shortcut."

    public enum ShortcutError: Error, Sendable, Equatable {
        case writeFailed(String)
        /// The destination `<name>.app` is occupied by something that ISN'T a Silo shortcut — refuse rather
        /// than delete a user's unrelated app/file/folder that happens to share the name.
        case destinationOccupied(String)
    }

    /// `Contents/Info.plist`. A per-game `CFBundleIdentifier` (from the deep link) keeps each shortcut a
    /// distinct LaunchServices identity; `LSUIElement` suppresses the Dock tile for the momentary stub.
    public func infoPlist() -> String {
        """
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleName</key><string>\(xmlEscaped(name))</string>
            <key>CFBundleDisplayName</key><string>\(xmlEscaped(name))</string>
            <key>CFBundleIdentifier</key><string>\(Self.bundleIDPrefix)\(bundleSafe(link.bundleIDComponent))</string>
            <key>CFBundleExecutable</key><string>launch</string>
            <key>CFBundlePackageType</key><string>APPL</string>
            <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
            <key>CFBundleShortVersionString</key><string>1.0</string>
            <key>LSApplicationCategoryType</key><string>public.app-category.games</string>
            <key>LSUIElement</key><true/>
            <key>LSMinimumSystemVersion</key><string>15.0</string>
        </dict>
        </plist>
        """
    }

    /// `Contents/MacOS/launch` — hands the `silo://…` deep link to `open` (which activates or launches Silo),
    /// then the stub exits. `exec` replaces the shell so nothing lingers.
    public func launchScript() -> String {
        """
        #!/bin/sh
        # Generated by Silo — launches \(name) via Silo.
        exec open \(shellQuoted(link.url.absoluteString))
        """
    }

    /// Write `<name>.app` into `directory`, marking the launch script executable. Returns the bundle URL.
    /// The `.app` file name is sanitized (path separators / colons → `-`) so a game whose name contains them
    /// can't escape `directory`; the *displayed* name (`CFBundleName`) keeps the original.
    @discardableResult
    public func write(into directory: URL, fileManager: FileManager = .default) throws -> URL {
        let app = directory.appendingPathComponent("\(fileSafeName).app", isDirectory: true)
        let macOS = app.appendingPathComponent("Contents/MacOS", isDirectory: true)
        // Replacing our OWN prior shortcut is fine (re-create is idempotent); deleting anything else — a
        // user's unrelated app/file/folder that happens to share the name — is not. Refuse in that case.
        if fileManager.fileExists(atPath: app.path), !Self.isSiloShortcut(at: app, fileManager: fileManager) {
            throw ShortcutError.destinationOccupied(app.lastPathComponent)
        }
        do {
            if fileManager.fileExists(atPath: app.path) { try fileManager.removeItem(at: app) }
            try fileManager.createDirectory(at: macOS, withIntermediateDirectories: true)
            try Data(infoPlist().utf8).write(
                to: app.appendingPathComponent("Contents/Info.plist"), options: .atomic)
            let script = macOS.appendingPathComponent("launch")
            try Data(launchScript().utf8).write(to: script, options: .atomic)
            try fileManager.setAttributes([.posixPermissions: 0o755], ofItemAtPath: script.path)
        } catch {
            throw ShortcutError.writeFailed((error as NSError).localizedDescription)
        }
        return app
    }

    /// Whether the item at `url` is one of Silo's own shortcut `.app`s — i.e. a bundle whose Info.plist
    /// `CFBundleIdentifier` carries our prefix. A plain file (no `Contents/Info.plist`) or any third-party
    /// bundle reads as `false`, so `write` never deletes it.
    static func isSiloShortcut(at url: URL, fileManager: FileManager = .default) -> Bool {
        let plistURL = url.appendingPathComponent("Contents/Info.plist")
        guard let data = fileManager.contents(atPath: plistURL.path),
              let plist = try? PropertyListSerialization.propertyList(from: data, format: nil),
              let id = (plist as? [String: Any])?["CFBundleIdentifier"] as? String
        else { return false }
        return id.hasPrefix(bundleIDPrefix)
    }

    // MARK: - Escaping

    /// A file-system-safe bundle name: the display name with path separators and colons neutralized (the
    /// characters HFS+/APFS forbid in a file name), so `<name>.app` stays a single component under `directory`.
    private var fileSafeName: String {
        let cleaned = name.map { "/:".contains($0) ? "-" : $0 }
        let joined = String(cleaned).trimmingCharacters(in: .whitespaces)
        return joined.isEmpty ? "Game" : joined
    }

    /// POSIX single-quote: wrap in `'…'`, rewriting embedded `'` as `'\''`. Safe for URLs/paths with anything.
    private func shellQuoted(_ s: String) -> String {
        "'" + s.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }
    private func xmlEscaped(_ s: String) -> String {
        s.replacingOccurrences(of: "&", with: "&amp;")
         .replacingOccurrences(of: "<", with: "&lt;")
         .replacingOccurrences(of: ">", with: "&gt;")
    }
    /// A bundle-id-safe slug (alphanumerics, `.` and `-` kept; anything else → `-`).
    private func bundleSafe(_ s: String) -> String {
        String(s.unicodeScalars.map {
            CharacterSet.alphanumerics.contains($0) || $0 == "." || $0 == "-" ? Character($0) : "-"
        })
    }
}
