import Foundation

/// Builds a standalone macOS `.app` that launches a game directly under GPTK — startable from Spotlight /
/// Dock / Launchpad without opening Silo. The bundle is categorized as a game (`public.app-category.games`),
/// which lets macOS **Game Mode** engage and prioritize CPU/GPU for it; because the `.app` directly execs
/// wine (it owns the process), the game category attributes to the running game.
///
/// The launch script is a *snapshot* of a resolved `LaunchPlan` (the same env Silo would launch with), so it
/// reflects the current GPTK/wine setup at generation time. Pure builders (`infoPlist`, `launchScript`) are
/// unit-tested; `write` performs the bundle I/O.
public struct GameAppShortcut: Sendable {
    public let name: String
    public let plan: LaunchPlan

    public init(name: String, plan: LaunchPlan) { self.name = name; self.plan = plan }

    public enum ShortcutError: Error, Sendable, Equatable { case writeFailed(String) }

    /// `Contents/Info.plist` — categorized as a game so macOS Game Mode can engage.
    public func infoPlist() -> String {
        """
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleName</key><string>\(xmlEscaped(name))</string>
            <key>CFBundleDisplayName</key><string>\(xmlEscaped(name))</string>
            <key>CFBundleIdentifier</key><string>com.silo.shortcut.\(bundleSafe(name))</string>
            <key>CFBundleExecutable</key><string>launch</string>
            <key>CFBundlePackageType</key><string>APPL</string>
            <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
            <key>CFBundleShortVersionString</key><string>1.0</string>
            <key>CFBundleIconFile</key><string>AppIcon</string>
            <key>LSApplicationCategoryType</key><string>public.app-category.games</string>
            <key>LSMinimumSystemVersion</key><string>14.0</string>
        </dict>
        </plist>
        """
    }

    /// `Contents/MacOS/launch` — exports the plan's resolved env, then execs wine. The `.app` is the process
    /// owner (so Game Mode attributes the game category to it).
    public func launchScript() -> String {
        var lines = ["#!/bin/sh", "# Generated by Silo — launches \(name) under GPTK/D3DMetal."]
        for key in plan.environment.keys.sorted() {
            lines.append("export \(key)=\(shellQuoted(plan.environment[key] ?? ""))")
        }
        lines.append("cd \(shellQuoted(plan.currentDirectory.path)) || exit 1")
        let command = ([plan.executable.path] + plan.arguments).map(shellQuoted).joined(separator: " ")
        lines.append("exec \(command)")
        return lines.joined(separator: "\n") + "\n"
    }

    /// Write `<name>.app` into `directory`, marking the launch script executable. Returns the bundle URL.
    @discardableResult
    public func write(into directory: URL, fileManager: FileManager = .default) throws -> URL {
        let app = directory.appendingPathComponent("\(name).app", isDirectory: true)
        let macOS = app.appendingPathComponent("Contents/MacOS", isDirectory: true)
        do {
            if fileManager.fileExists(atPath: app.path) { try fileManager.removeItem(at: app) }
            try fileManager.createDirectory(at: macOS, withIntermediateDirectories: true)
            try Data(infoPlist().utf8).write(to: app.appendingPathComponent("Contents/Info.plist"))
            let script = macOS.appendingPathComponent("launch")
            try Data(launchScript().utf8).write(to: script)
            try fileManager.setAttributes([.posixPermissions: 0o755], ofItemAtPath: script.path)
        } catch {
            throw ShortcutError.writeFailed((error as NSError).localizedDescription)
        }
        return app
    }

    // MARK: - Escaping

    /// POSIX single-quote: wrap in `'…'`, rewriting embedded `'` as `'\''`. Safe for paths with spaces/quotes.
    private func shellQuoted(_ s: String) -> String {
        "'" + s.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }
    private func xmlEscaped(_ s: String) -> String {
        s.replacingOccurrences(of: "&", with: "&amp;")
         .replacingOccurrences(of: "<", with: "&lt;")
         .replacingOccurrences(of: ">", with: "&gt;")
    }
    /// A bundle-id-safe slug (alphanumerics kept, anything else → `-`).
    private func bundleSafe(_ s: String) -> String {
        String(s.unicodeScalars.map { CharacterSet.alphanumerics.contains($0) ? Character($0) : "-" })
    }
}
